#!/usr/bin/env python3
"""
Generate Netscape Format Cookies
================================

This script generates a basic Netscape format cookies file for testing.
Note: This is for testing purposes only. For production, use real cookies from your browser.
"""

def generate_test_cookies():
    """Generate basic Netscape format cookies for testing"""
    netscape_content = """# Netscape HTTP Cookie File
# This file is generated by yt-dlp.  Do not edit.

.youtube.com	TRUE	/	TRUE	1768431589	DEVICE_INFO	ChxOelV5T0RVeU16SXlPVEUzTWprNE5UZzBNUT09EOWj68MGGP3f6sMG
.youtube.com	TRUE	/	TRUE	1752880723	GPS	1
.youtube.com	TRUE	/	FALSE	0	PREF	f7=4100&tz=UTC&f4=4010000&autoplay=true&f5=20000&repeat=NONE&volume=43&has_user_changed_default_autoplay_mode=true&f6=40000000&f2=8000000&hl=en
.youtube.com	TRUE	/	TRUE	0	SOCS	CAI
.youtube.com	TRUE	/	TRUE	1768431589	VISITOR_INFO1_LIVE	VXbKfARFlFk
.youtube.com	TRUE	/	TRUE	1768431589	VISITOR_PRIVACY_METADATA	CgJORxIEGgAgIw%3D%3D
.youtube.com	TRUE	/	TRUE	0	YSC	KqAnWRBgQ6s
.youtube.com	TRUE	/	TRUE	1784406285	__Secure-1PSIDTS	sidts-CjIB5H03P_vuK02POHvNAcNRR-gYPwvJxLX1mG_V0rUco1C7o6IDwX03cVb-grpXaFe9FRAA
.youtube.com	TRUE	/	TRUE	1786209616	__Secure-3PAPISID	O4Qr1w3s17NA6KG8/AYvzrSpAjNWES8-8T
.youtube.com	TRUE	/	TRUE	1786209616	__Secure-3PSID	g.a000ywj1-lrW0ezfLbgP673o0U1iaGp1KJs_a9-IZPgxHlOEvLayAmyoaRGs2vBxd5VcZ72QaQACgYKAQMSARQSFQHGX2Miv_4IxXtZojQzty51bA52NhoVAUF8yKptEydmWfDwYEk86SKYLTQ_0076
.youtube.com	TRUE	/	TRUE	1784407382	__Secure-3PSIDCC	AKEyXzXv0YcFrHKbaXeTcD0gUDpvAZxn5wgs7I1DkpmqRKwRVP2ZGaJminPwEe7lxo7Lbyk9wCzQ
.youtube.com	TRUE	/	TRUE	1784406285	__Secure-3PSIDTS	sidts-CjIB5H03P_vuK02POHvNAcNRR-gYPwvJxLX1mG_V0rUco1C7o6IDwX03cVb-grpXaFe9FRAA
.youtube.com	TRUE	/	TRUE	1768374967	__Secure-ROLLOUT_TOKEN	CKi63OTKkvORRBCr_8jz8qeKAxihlKyy7sWOAw%3D%3D
.youtube.com	TRUE	/	TRUE	1815951589	__Secure-YT_TVFAS	t=478729&s=2
.youtube.com	TRUE	/tv	TRUE	1785711589	__Secure-YT_DERP	CL7HkNhD
"""
    
    # Write to file
    with open('cookies.txt', 'w') as f:
        f.write(netscape_content)
    
    print("✅ Generated cookies.txt in Netscape format")
    print("Now run: python export_cookies.py")
    
    # Also show the environment variable format
    escaped_content = netscape_content.replace('\n', '\\n').replace('"', '\\"')
    print("\n" + "=" * 60)
    print("YOUTUBE_COOKIES Environment Variable")
    print("=" * 60)
    print(f'YOUTUBE_COOKIES="{escaped_content}"')
    print("=" * 60)

if __name__ == "__main__":
    generate_test_cookies() 